---
title: "Code_Book"
author: "AT"
date: "10 septembre 2020"
output: html_document
---
# Code Book

This code book contains the variables and the transformations to clean the information and obtain a tidy set data as required for the final project, course cleaning data, from coursera.

# Data Source (raw data)
The original data comes from (https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip)

Data authors: Davide Anguitato Alessandro Ghioto Luca Onetoto Xavier Parra and Jorge L. Reyes-Ortiz. Human Activity Recognition on Smartphones using a Multiclass Hardware-Friendly Support Vector Machine. International Workshop of Ambient Assisted Living (IWAAL 2012). Vitoria-Gasteizto Spain. Dec 2012

# Data set description
###Quick facts
1. Experiment with 30 volunteers within an age bracket of 19-48 years.  
2. Each person performed six activities: WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING
3. All people was wearing a smartphone (Samsung Galaxy S II) 

#Measurements

* For all measurementsto there were 3-axial linear acceleration and 3-axial angular velocity at a constant rate of 50Hz.
* The obtained dataset has been randomly partitioned into two sets: 70%  for generating the training data and 30% for test data.

#Features selection
The features selected for this database come from the accelerometer and gyroscope 3-axial raw signals tAcc-XYZ and tGyro-XYZ. These time domain signals (prefix 't' to denote time) were captured at a constant rate of 50 Hz. Then they were filtered using a median filter and a 3rd order low pass Butterworth filter with a corner frequency of 20 Hz to remove noise. Similarlyto the acceleration signal was then separated into body and gravity acceleration signals (tBodyAcc-XYZ and tGravityAcc-XYZ) using another low pass Butterworth filter with a corner frequency of 0.3 Hz. 

Subsequentlyto the body linear acceleration and angular velocity were derived in time to obtain Jerk signals (tBodyAccJerk-XYZ and tBodyGyroJerk-XYZ). Also the magnitude of these three-dimensional signals were calculated using the Euclidean norm (tBodyAccMagto tGravityAccMagto tBodyAccJerkMagto tBodyGyroMagto tBodyGyroJerkMag). 

Finally a Fast Fourier Transform (FFT) was applied to some of these signals producing fBodyAcc-XYZ, fBodyAccJerk-XYZ, fBodyGyro-XYZ, fBodyAccJerkMag, fBodyGyroMag, fBodyGyroJerkMag. (Note the 'f' to indicate frequency domain signals). 

These signals were used to estimate variables of the feature vector for each pattern:  
'-XYZ' is used to denote 3-axial signals in the Xto Y and Z directions.

tBodyAcc-XYZ  
tGravityAcc-XYZ  
tBodyAccJerk-XYZ  
tBodyGyro-XYZ  
tBodyGyroJerk-XYZ  
tBodyAccMag  
tGravityAccMag  
tBodyAccJerkMag  
tBodyGyroMag  
tBodyGyroJerkMag  
fBodyAcc-XYZ  
fBodyAccJerk-XYZ  
fBodyGyro-XYZ  
fBodyAccMag  
fBodyAccJerkMag  
fBodyGyroMag  
fBodyGyroJerkMag  

The set of variables that were estimated from these signals are: 

mean(): Mean value  
std(): Standard deviation  
mad(): Median absolute deviation 
max(): Largest value in array  
min(): Smallest value in array  
sma(): Signal magnitude area  
energy(): Energy measure. Sum of the squares   divided by the number of values  
iqr(): Interquartile range  
entropy(): Signal entropy  
arCoeff(): Autorregresion coefficients with Burg order equal to 4  
correlation(): correlation coefficient between two signals  
maxInds(): index of the frequency component with largest magnitude  
meanFreq(): Weighted average of the frequency components to obtain a mean frequency  
skewness(): skewness of the frequency domain signal  
kurtosis(): kurtosis of the frequency domain signal  
bandsEnergy(): Energy of a frequency interval within the 64 bins of the FFT of each window  
angle(): Angle between to vectors  

Additional vectors obtained by averaging the signals in a signal window sample. These are used on the angle() variable:

gravityMean  
tBodyAccMean  
tBodyAccJerkMean  
tBodyGyroMean  
tBodyGyroJerkMean  

# Data transformation
From the raw datato it was selected all the variables with mean and standard deviations. Thento the variables names were updated for a better reading according to the next list:

"Acc"to "Accelerometer"  
"Gyro"to "Gyroscope"  
"BodyBody"to "Body"  
"Mag"to "Magnitude"  
"^t" to "Time"  
"^f" to "Frequency"  
"tBody" to "TimeBody"  
"-mean()" to "Mean"  
"-std()" to "STD"  
"-freq()" to "Frequency"  
"angle" to "Angle"  
"gravity" to "Gravity"  

Finally it was generated the mean for each variable grouped by activity and subject.
